


INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("ルフィー",50,3000);

INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("ゾロ",80,3000);

INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("ナミ",80,3000);

INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("ウソップ",60,4000);

INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("サンジ",60,5000);

INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("チョッパー",30,6000);

INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("ロビン",30,3000);

INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("フランキー",30,3000);

INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("ブルック",60,3000);

INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("エース",20,4000);

INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("サボ",60,5000);

INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("ジンベエ",30,6000);

INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("ロジャー",50,9000);

INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("アーロン",60,2000);

INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("クロコダイル",40,10000);

INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("ビビ",30,1000);





INSERT INTO CUSTOMER_INFO(CUSTOMER_NAME,CUSTOMER_PASS,MAILADDRESS,POSTCODE,ADDRESS,TELNUMBER
)VALUES(
"ikeda","ikeda123","ikeda@ikeda.co.jp","1234567","東京都八王子市xxx","09012345678");
INSERT INTO CUSTOMER_INFO(CUSTOMER_NAME,CUSTOMER_PASS,MAILADDRESS,POSTCODE,ADDRESS,TELNUMBER
)VALUES(
"kuriya","kuriya","kuriya@kuriya.co.jp","1234567","東京都xxx","09012345678");

INSERT INTO CUSTOMER_INFO(CUSTOMER_NAME,CUSTOMER_PASS,MAILADDRESS,POSTCODE,ADDRESS,TELNUMBER
)VALUES(
"hosoya","hosoya","hosoya@hosoya.co.jp","1234567","東京都xxx","09012345678");

INSERT INTO CUSTOMER_INFO(CUSTOMER_NAME,CUSTOMER_PASS,MAILADDRESS,POSTCODE,ADDRESS,TELNUMBER
)VALUES(
"wada","wada","wada@wada.co.jp","1234567","東京都xxx","09012345678");








